[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Anthropic", "Model", "Provider"]
license = ["Apache-2.0"]
name = "ai.model.provider.anthropic"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.model.provider.anthropic"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true
