[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Anthropic", "Model", "Provider"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.anthropic"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.anthropic"
version = "1.3.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.anthropic-native"
version = "1.3.0"
path = "../native/build/libs/ai.anthropic-native-1.3.0-SNAPSHOT.jar"
